3. SINIF/1. Yarıyıl/Veritabanı Yönetim Sistemleri/Proje/MvcBlog/MvcBlog/Controllers/AdminMakaleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcBlog.Models;
using System.Web.Helpers;
using System.IO;
using PagedList;
using PagedList.Mvc;
using System.Data.SqlClient;

namespace MvcBlog.Controllers
{
    public class AdminMakaleController : Controller
    {
        mvcblogDB db = new mvcblogDB();
        // GET: AdminMakale
        public ActionResult Index(int Page=1)
        {
            var makales = db.Makales.SqlQuery("Select * from Makale").ToPagedList(Page, 10);
                //OrderByDescending(m=>m.Makaleid).ToPagedList(Page,10);
            return View(makales);
        }

        // GET: AdminMakale/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: AdminMakale/Create
        public ActionResult Create()
        {
            ViewBag.Kategoriid = new SelectList(db.Kategoris, "Kategoriid", "KategoriAdi");
            return View();
        }

        // POST: AdminMakale/Create
        [HttpPost]
        public ActionResult Create(Makale makale,string etiketler,HttpPostedFileBase Foto )
        {
            //Model kısmında çalışacak komutlar
            if (ModelState.IsValid)
            {
                if (Foto != null)
                {
                    WebImage img = new WebImage(Foto.InputStream);
                    FileInfo fotoinfo = new FileInfo(Foto.FileName);

                    string newfoto = Guid.NewGuid().ToString() + fotoinfo.Extension;
                    img.Resize(800, 350);
                    img.Save("~/Uploads/MakaleFoto/" + newfoto);
                    makale.Foto = "/Uploads/MakaleFoto/" + newfoto;
                    
                }
                if (etiketler != null)
                {
                    string[] etiketdizi = etiketler.Split(',');
                    foreach (var i in etiketdizi)
                    {
                        var yenietiket = new Etiket { EtiketAdi = i };
                        db.Etikets.Add(yenietiket);
                        makale.Etikets.Add(yenietiket);
                    }
                }
                makale.Uyeid = Convert.ToInt32(Session["uyeid"]);
                makale.Okuma = 1;
                db.Makales.Add(makale);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
                
                
                return View(makale);
            
        }

        // GET: AdminMakale/Edit/5
        public ActionResult Edit(int id)
        {
            var makale = db.Makales.Where(m => m.Makaleid == id).SingleOrDefault();
            if (makale == null)
            {
                return HttpNotFound();
            }
            ViewBag.Kategoriid = new SelectList(db.Kategoris, "Kategoriid", "KategoriAdi", makale.Kategoriid);
            return View(makale);
        }

        // POST: AdminMakale/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, HttpPostedFileBase Foto,Makale makale)
        {
            try
            {
                // Makales te değişkilik yapılacak
                var makales = db.Makales.Where(m => m.Makaleid == id).SingleOrDefault();
                if (Foto != null)
                {
                    if (System.IO.File.Exists(Server.MapPath(makales.Foto))) 
                    {
                        System.IO.File.Delete(Server.MapPath(makales.Foto));
                    }
                    WebImage img = new WebImage(Foto.InputStream);
                    FileInfo fotoinfo = new FileInfo(Foto.FileName);

                    string newfoto = Guid.NewGuid().ToString() + fotoinfo.Extension;
                    img.Resize(800, 350);
                    img.Save("~/Uploads/MakaleFoto/" + newfoto);
                    makales.Foto = "/Uploads/MakaleFoto/" + newfoto;
                    makales.Baslik = makale.Baslik;
                    makales.Icerik = makale.Icerik;
                    makales.Kategoriid = makale.Kategoriid;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View();
            }
            catch
            {
                ViewBag.Kategoriid = new SelectList(db.Kategoris, "Kategoriid", "KategoriAdi", makale.Kategoriid);
                return View(makale);
            }
        }

        // GET: AdminMakale/Delete/5
        public ActionResult Delete(int id)
        {

            var makale = db.Makales.Where(m => m.Makaleid == id).SingleOrDefault();
            if (makale == null)
            {
                return HttpNotFound();
            }
            return View(makale);
        }

        // POST: AdminMakale/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id, FormCollection collection)
        {
            try
            {
                // Etiket yorum foto makale her şeyi silmemiz lazım
                var makales = db.Makales.Where(m => m.Makaleid == id).SingleOrDefault();
                if (makales == null)
                {
                    return HttpNotFound();
                }
                if (System.IO.File.Exists(Server.MapPath(makales.Foto))) 
                {
                    System.IO.File.Delete(Server.MapPath(makales.Foto));
                }
                foreach(var i in makales.Yorums.ToList())
                {
                    db.Yorums.Remove(i);
                }
                foreach(var i in makales.Etikets.ToList())
                {
                    db.Etikets.Remove(i);
                }
                db.Database.ExecuteSqlCommand("delete from Makale where Makaleid=@Ara", new SqlParameter("@Ara", id));
                    //Makales.Remove(makales);
                db.SaveChanges();


                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }
    }
}

3. SINIF/1. Yarıyıl/Veritabanı Yönetim Sistemleri/Proje/MvcBlog/MvcBlog/Views/AdminMakale/Create.cshtml
@model MvcBlog.Models.Makale

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 class="card-header">Makale Oluştur</h2>

@*Makalefoto klasörüne kayıt için bunu yazmazsak olmuyor*@

@using (Html.BeginForm("Create","AdminMakale",FormMethod.Post,new {enctype="multipart/form-data"}))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Makale</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Kategoriid, "Kategoriid", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Kategoriid", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Kategoriid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Baslik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Baslik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Baslik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Icerik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Icerik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Icerik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="Foto" id="Foto" accept=".jpg,.png,.gif,.JPEG,.jpeg" class="form-control" />
                @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tarih, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tarih, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                @Html.ValidationMessageFor(model => model.Tarih, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
           @Html.Label("Etiketler", new {@class="control-label col-md-2"})
            <div class="col-md-10">
                @Html.TextBox("Etiketler")
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Geri Dön", "Index")
</div>

3. SINIF/1. Yarıyıl/Veritabanı Yönetim Sistemleri/Proje/MvcBlog/MvcBlog/Views/AdminMakale/Delete.cshtml
@model MvcBlog.Models.Makale

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Makale</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Kategori.KategoriAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kategori.KategoriAdi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Uye.KullaniciAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Uye.KullaniciAdi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Baslik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Baslik)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Icerik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Icerik)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Foto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Foto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tarih)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tarih)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Okuma)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Okuma)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

3. SINIF/1. Yarıyıl/Veritabanı Yönetim Sistemleri/Proje/MvcBlog/MvcBlog/Views/AdminMakale/Edit.cshtml
@model MvcBlog.Models.Makale

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 class="card-header">Düzenle</h2>

@using (Html.BeginForm("Edit", "AdminMakale", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Makale Düzenle</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Makaleid)

        <div class="form-group">
            @Html.LabelFor(model => model.Baslik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Baslik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Baslik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Icerik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Icerik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Icerik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Eski Foto" , htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img width="75" src="@Model.Foto" alt="Alternate Text" />
                @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="Foto" id="Foto" accept=".jpg,.png,.gif,.JPEG,.jpeg" class="form-control" />
                @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tarih, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tarih, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tarih, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Kategoriid, "Kategoriid", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Kategoriid", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Kategoriid, "", new { @class = "text-danger" })
            </div>
        </div>

        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Geri Dön", "Index")
</div>

3. SINIF/1. Yarıyıl/Veritabanı Yönetim Sistemleri/Proje/MvcBlog/MvcBlog/Views/AdminMakale/Index.cshtml
@using PagedList
@using PagedList.Mvc

@model IPagedList<MvcBlog.Models.Makale>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 class="card-header">Makaleler</h2>

<p>
    @Html.ActionLink("Yeni Makale", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.Label("Kategori Adı")
        </th>
        <th>
            @Html.Label("Başlık")
        </th>
        
        <th>
            @Html.Label("Foto")
        </th>
        <th>
            @Html.Label("Tarih")
        </th>
        <th>
            @Html.Label("Okunma")
        </th>
        
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Kategori.KategoriAdi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Baslik)
        </td>
        
        <td>
           <img width="75" img src="@item.Foto"/>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Tarih)
        </td>
        
        <td>
            @Html.DisplayFor(modelItem => item.Okuma)
        </td>
        <td>
            @Html.ActionLink("Düzenle", "Edit", new { id=item.Makaleid }) |
            @Html.ActionLink("Detay", "Details", new { id=item.Makaleid }) |
            @Html.ActionLink("Sil", "Delete", new { id=item.Makaleid })
        </td>
    </tr>
}

</table>
<div class="row">
    <div class="col-md-8 text-center">
        <div class="pagedList pagination-lg ">
            @Html.PagedListPager(Model, Page => Url.Action("Index", new { Page }), PagedListRenderOptions.Classic)

        </div>

    </div>

</div>