2. SINIF/1. Yarıyıl/Web Programlama/Proje/Proje Ödevi/Web Programlama Dersi Proje Ödevi/Models/User.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>

//@Web_Programlama_Dersi_Proje_Ödevi.Resources.hometext
//------------------------------------------------------------------------------

namespace Web_Programlama_Dersi_Proje_Ödevi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Sepet = new HashSet<Sepet>();
        }
    
        public int UserId { get; set; }

        [DisplayName("Kullanıcı Adı")]
        public string UserName { get; set; }
        [DisplayName("Şifre")]
        [DataType(DataType.Password)]
        public string UserPassword { get; set; }
        [DisplayName("Admin Mi ??")]
        public Nullable<bool> IsAdmin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sepet> Sepet { get; set; }
    }
}

2. SINIF/1. Yarıyıl/Web Programlama/Proje/Proje Ödevi/Web Programlama Dersi Proje Ödevi/Controllers/SepetsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Web_Programlama_Dersi_Proje_Ödevi.Models;

namespace Web_Programlama_Dersi_Proje_Ödevi.Controllers
{
    public class SepetsController : Controller
    {
        private SauCarEntities6 db = new SauCarEntities6();

        // GET: Sepets
        public ActionResult Index()
        {
            if (Session["IsAdmin"] != null)
            {
                var sepet = db.Sepet.Include(s => s.Arac).Include(s => s.User);
                return View(sepet.ToList());
            }
            else
            {
                return RedirectToAction("Profil", "Users", new { id = Session["UserId"] });
            }

        }

        // GET: Sepets/Details/5
        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            }
            Sepet sepet = db.Sepet.Find(id);
            if (sepet == null)
            {
                return HttpNotFound();
            }
            return View(sepet);
        }

        // GET: Sepets/Create
        public ActionResult Create()
        {
            ViewBag.SepetAracId = new SelectList(db.Arac, "AracId", "AracModel");
            ViewBag.SepetUserID = new SelectList(db.User, "UserId", "UserName");
            return View();
        }

        // POST: Sepets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SepetUserID,SepetAracId,SepetAlimTarihi,SepetTeslimTarihi,SepetID")] Sepet sepet)
        {
            if (ModelState.IsValid)
            {
                db.Sepet.Add(sepet);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.SepetAracId = new SelectList(db.Arac, "AracId", "AracModel", sepet.SepetAracId);
            ViewBag.SepetUserID = new SelectList(db.User, "UserId", "UserName", sepet.SepetUserID);
            return View(sepet);
        }

        // GET: Sepets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sepet sepet = db.Sepet.Find(id);
            if (sepet == null)
            {
                return HttpNotFound();
            }
            ViewBag.SepetAracId = new SelectList(db.Arac, "AracId", "AracModel", sepet.SepetAracId);
            ViewBag.SepetUserID = new SelectList(db.User, "UserId", "UserName", sepet.SepetUserID);
            return View(sepet);
        }

        // POST: Sepets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SepetUserID,SepetAracId,SepetAlimTarihi,SepetTeslimTarihi,SepetID")] Sepet sepet)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sepet).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.SepetAracId = new SelectList(db.Arac, "AracId", "AracModel", sepet.SepetAracId);
            ViewBag.SepetUserID = new SelectList(db.User, "UserId", "UserName", sepet.SepetUserID);
            return View(sepet);
        }

        // GET: Sepets/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sepet sepet = db.Sepet.Find(id);
            if (sepet == null)
            {
                return HttpNotFound();
            }
            return View(sepet);
        }

        // POST: Sepets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Sepet sepet = db.Sepet.Find(id);
            db.Sepet.Remove(sepet);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

2. SINIF/1. Yarıyıl/Web Programlama/Proje/Proje Ödevi/Web Programlama Dersi Proje Ödevi/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Web_Programlama_Dersi_Proje_Ödevi.Models;

namespace Web_Programlama_Dersi_Proje_Ödevi.Controllers
{
    public class UsersController : Controller
    {
        private SauCarEntities6 db = new SauCarEntities6();

        // GET: Users
        public ActionResult Index()
        {
            return View(db.User.ToList());
        }

        // GET: Users/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.User.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }
        public ActionResult Profil(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.User.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserId,UserName,UserPassword,IsAdmin")] User user)
        {
            if (ModelState.IsValid)
            {
                db.User.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(user);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.User.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserId,UserName,UserPassword,IsAdmin")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.User.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = db.User.Find(id);
            db.User.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

2. SINIF/1. Yarıyıl/Web Programlama/Proje/Proje Ödevi/Web Programlama Dersi Proje Ödevi/Views/Users/Create.cshtml
@model Web_Programlama_Dersi_Proje_Ödevi.Models.User

@{
    ViewBag.Title = Web_Programlama_Dersi_Proje_Ödevi.Resources.hometext.KayitOl;
    if (Session["Isadmin"] == null) { Response.Redirect("~/GirisKayitIslemleri/Giris"); }
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br /><br /><br /><br /><br /><br />
@using (Html.BeginForm()) 
{
    
    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsAdmin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsAdmin)
                    @Html.ValidationMessageFor(model => model.IsAdmin, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@Web_Programlama_Dersi_Proje_Ödevi.Resources.hometext.Kaydet" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Geri Dön..", "Index")
</div>
<br /><br /><br /><br /><br />

2. SINIF/1. Yarıyıl/Web Programlama/Proje/Proje Ödevi/Web Programlama Dersi Proje Ödevi/Views/Users/Delete.cshtml
@model Web_Programlama_Dersi_Proje_Ödevi.Models.User

@{
    ViewBag.Title = Web_Programlama_Dersi_Proje_Ödevi.Resources.hometext.Sil;
    if (Session["Isadmin"] == null) { Response.Redirect("~/GirisKayitIslemleri/Giris"); }
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<br /><br /><br /><br /><br /><br /><br /><br /><br />
<center>

    <dl class="dl-horizontal" style="margin-top:20px">
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserPassword)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserPassword)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsAdmin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsAdmin)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="@Web_Programlama_Dersi_Proje_Ödevi.Resources.hometext.Sil" class="btn btn-danger" /> |
            @Html.ActionLink(@Web_Programlama_Dersi_Proje_Ödevi.Resources.hometext.GeriDön, "Index")
        </div>
    }
</center>
<br /><br /><br /><br /><br /><br /><br />

2. SINIF/1. Yarıyıl/Web Programlama/Proje/Proje Ödevi/Web Programlama Dersi Proje Ödevi/Views/Users/Details.cshtml
@model Web_Programlama_Dersi_Proje_Ödevi.Models.User

@{
    ViewBag.Title = Web_Programlama_Dersi_Proje_Ödevi.Resources.hometext.Detaylar;
    if (Session["Isadmin"] == null) { Response.Redirect("~/GirisKayitIslemleri/Giris"); }
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br /><br /><br /><br /><br /><br /><br /><br />
<center>

    <dl class="dl-horizontal" style="margin-top:13px">
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserPassword)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserPassword)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsAdmin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsAdmin)
        </dd>

    </dl>
</center>
<center>
    @Html.ActionLink(@Web_Programlama_Dersi_Proje_Ödevi.Resources.hometext.Düzenle, "Edit", new { id = Model.UserId }) |
    @Html.ActionLink(@Web_Programlama_Dersi_Proje_Ödevi.Resources.hometext.GeriDön, "Index")
</center>
<br /><br /><br /><br /><br /><br /><br /><br /><br />

2. SINIF/1. Yarıyıl/Web Programlama/Proje/Proje Ödevi/Web Programlama Dersi Proje Ödevi/Views/Users/Edit.cshtml
@model Web_Programlama_Dersi_Proje_Ödevi.Models.User

@{
    ViewBag.Title = Web_Programlama_Dersi_Proje_Ödevi.Resources.hometext.Düzenle;
    if (Session["Isadmin"] == null) { Response.Redirect("~/GirisKayitIslemleri/Giris"); }
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br /><br /><br /><br /><br /><br />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.UserId)

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsAdmin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsAdmin)
                    @Html.ValidationMessageFor(model => model.IsAdmin, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@Web_Programlama_Dersi_Proje_Ödevi.Resources.hometext.Kaydet" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink(@Web_Programlama_Dersi_Proje_Ödevi.Resources.hometext.GeriDön, "Index")
</div>
<br /><br /><br /><br /><br /><br />

2. SINIF/1. Yarıyıl/Web Programlama/Proje/Proje Ödevi/Web Programlama Dersi Proje Ödevi/Views/Users/Index.cshtml
@model IEnumerable<Web_Programlama_Dersi_Proje_Ödevi.Models.User>

@{
    ViewBag.Title = Web_Programlama_Dersi_Proje_Ödevi.Resources.hometext.Kullanıcılar;
    if (Session["Isadmin"] == null)
    {
        Response.Redirect("~/GirisKayitIslemleri/Giris");
    }
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br /><br /><br /><br /><br /><br /><br />
<p>
    @Html.ActionLink(@Web_Programlama_Dersi_Proje_Ödevi.Resources.hometext.Ekle, "Create")
</p>
<table class="table" style="margin-top:30px">
    <tr>
        <th>
            @Web_Programlama_Dersi_Proje_Ödevi.Resources.hometext.KullanıcıAdı
        </th>
        <th>
            @Web_Programlama_Dersi_Proje_Ödevi.Resources.hometext.sifre
        </th>
        <th>
            @Web_Programlama_Dersi_Proje_Ödevi.Resources.hometext.admin
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserPassword)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsAdmin)
        </td>
        <td>
            @Html.ActionLink(@Web_Programlama_Dersi_Proje_Ödevi.Resources.hometext.Düzenle, "Edit", new { id=item.UserId }) |
            @Html.ActionLink(@Web_Programlama_Dersi_Proje_Ödevi.Resources.hometext.Detaylar, "Details", new { id=item.UserId }) |
            @Html.ActionLink(@Web_Programlama_Dersi_Proje_Ödevi.Resources.hometext.Sil, "Delete", new { id=item.UserId })
        </td>
    </tr>
}

</table>
<br /><br /><br /><br /><br /><br /><br />

2. SINIF/1. Yarıyıl/Web Programlama/Proje/Proje Ödevi/Web Programlama Dersi Proje Ödevi/Views/Users/Profil.cshtml
@model Web_Programlama_Dersi_Proje_Ödevi.Models.User

@{
    ViewBag.Title = Web_Programlama_Dersi_Proje_Ödevi.Resources.hometext.profil;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Profil</h2>

<br /><br /><br /><br /><br /><br />


<table class="table">
    <tr>
        <th>
            @Web_Programlama_Dersi_Proje_Ödevi.Resources.hometext.AlimTarihi
        </th>
        <th>
            @Web_Programlama_Dersi_Proje_Ödevi.Resources.hometext.TeslimTarihi
        </th>
        <th>
            @Web_Programlama_Dersi_Proje_Ödevi.Resources.hometext.AracModel
        </th>
        <th>
            @Web_Programlama_Dersi_Proje_Ödevi.Resources.hometext.KullanıcıAdı
        </th>
    </tr>

@foreach (var item in Model.Sepet) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.SepetAlimTarihi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SepetTeslimTarihi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Arac.AracModel)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.User.UserName)
        </td>
        <td>
            @Html.ActionLink(Web_Programlama_Dersi_Proje_Ödevi.Resources.hometext.adminsepettencikar, "Delete","Sepets", new { id = item.SepetID },null)
        </td>
    </tr>
}

</table>
<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
<br /><br /><br />